/* Stub for Mesa's generated workaround list: the EU encoder/decoder does not use it. */
#ifndef INTEL_WA_H
#define INTEL_WA_H
#include "util/macros.h"
enum intel_workaround_id { INTEL_WA_14012437816 = 0, INTEL_WA_NUM = 1 };
#define INTEL_WA_14012437816_GFX_VER 0
enum intel_wa_steppings { INTEL_STEPPING_A0 = 0, INTEL_STEPPING_B0, INTEL_STEPPING_C0, INTEL_STEPPING_D0, INTEL_STEPPING_E0, INTEL_STEPPING_F0, INTEL_STEPPING_G0, INTEL_STEPPING_H0, INTEL_STEPPING_I0, INTEL_STEPPING_J0, INTEL_STEPPING_K0, INTEL_STEPPING_L0, INTEL_STEPPING_M0, INTEL_STEPPING_N0, INTEL_STEPPING_O0, INTEL_STEPPING_P0, INTEL_STEPPING_RELEASE };
#endif
